In [20]:
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# 타이타닉 데이터셋 로드
df = sns.load_dataset('titanic')

##  train_test_split
- 하이퍼파라미터
    - test_size
    - train_size
    - radom_state
    - shuffle =True, False 데이터 분할 전에 섞는 것
    - statify = y 타겟변수 층화샘플링도 가능하다.

In [2]:
import pandas as pd
df['sex'] = df['sex'].map({'male':0, 'female':1})
df=pd.get_dummies(df, columns=['embarked'], drop_first=True)

In [3]:
# 학습데이터셋 정리

X = df[['sex','age','fare','embarked_Q','embarked_S']]
y = df['survived']

In [4]:
#train_test_split 나눈다.

X_train, X_test, y_train, y_test=train_test_split(
    X,y,
    test_size= 0.2)

In [5]:
print(X_train, y_train)

     sex   age     fare  embarked_Q  embarked_S
273    0  37.0   29.700           0           0
386    0   1.0   46.900           0           1
716    1  38.0  227.525           0           0
134    0  25.0   13.000           0           1
825    0   NaN    6.950           1           0
..   ...   ...      ...         ...         ...
387    1  36.0   13.000           0           1
556    1  48.0   39.600           0           0
166    1   NaN   55.000           0           1
66     1  29.0   10.500           0           1
789    0  46.0   79.200           0           0

[712 rows x 5 columns] 273    0
386    0
716    1
134    0
825    0
      ..
387    1
556    1
166    1
66     1
789    0
Name: survived, Length: 712, dtype: int64


X_train, X_test, y_train, y_test=train_test_split(
    X,y,
    test_size= 0.2,
    stratify = y)

print(X_train, y_train, y_test)

In [6]:
#스케일링 진행
scaler=StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [7]:
print(y.value_counts(normalize=True))

0    0.616162
1    0.383838
Name: survived, dtype: float64

In [8]:
print(y_train.value_counts(normalize=True))

0    0.617978
1    0.382022
Name: survived, dtype: float64

In [9]:
print(y_test.value_counts(normalize=True))

0    0.608939
1    0.391061
Name: survived, dtype: float64

- train_test_split 데이터를 자르는 방법, 어떻게 데이터를 자르는가?

### 교차검증 cross_val
- 반복적으로 교차 검증을 하는 것 위에 train_test_split 이거와 비슷하지만 다른 뜻을 의미한다.

In [10]:
## 교차검증
## k-fold Sk-fold

from sklearn.model_selection import KFold, StratifiedKFold

In [11]:
#폴드를 가지고 오는 건 간단하다!
#폴드를 가지고 온다 의미
kf = KFold(n_splits = 5)
skf = StratifiedKFold(n_splits = 5)

In [12]:
X

     sex   age     fare  embarked_Q  embarked_S
0      0  22.0   7.2500           0           1
1      1  38.0  71.2833           0           0
2      1  26.0   7.9250           0           1
3      1  35.0  53.1000           0           1
4      0  35.0   8.0500           0           1
..   ...   ...      ...         ...         ...
886    0  27.0  13.0000           0           1
887    1  19.0  30.0000           0           1
888    1   NaN  23.4500           0           1
889    0  26.0  30.0000           0           0
890    0  32.0   7.7500           1           0

[891 rows x 5 columns]

In [13]:
from collections import Counter
# Kfold의 값을 넣어서 나누면 된다.
# kf.split(X)
kf_target_dis=[Counter(y.iloc[test_idx]) for _, test_idx in kf.split(X)]

In [14]:
# skf.split()
# skf.split(X,y) 클래스값도 꼭 같이 넣어줘야 한다. 
# 클래스 값이 어떤 분포인지에 따라 비율로 나누려고 한다.
skf_target_dis=[Counter(y.iloc[test_idx]) for _, test_idx in skf.split(X,y)] #

In [15]:
kf_target_dis

[Counter({0: 120, 1: 59}),
 Counter({0: 99, 1: 79}),
 Counter({0: 109, 1: 69}),
 Counter({1: 72, 0: 106}),
 Counter({0: 115, 1: 63})]

In [16]:
skf_target_dis

[Counter({0: 110, 1: 69}),
 Counter({0: 110, 1: 68}),
 Counter({1: 68, 0: 110}),
 Counter({1: 68, 0: 110}),
 Counter({1: 69, 0: 109})]

## 교차검증
- kf, skf ->데이터셋을 나눠서 진행한다. 
- 교차검증을 반복문으로 진행해도 되고, cross_val_score Sklearn에서 제공하는 패키지로도 가능하다!

In [17]:
X

     sex   age     fare  embarked_Q  embarked_S
0      0  22.0   7.2500           0           1
1      1  38.0  71.2833           0           0
2      1  26.0   7.9250           0           1
3      1  35.0  53.1000           0           1
4      0  35.0   8.0500           0           1
..   ...   ...      ...         ...         ...
886    0  27.0  13.0000           0           1
887    1  19.0  30.0000           0           1
888    1   NaN  23.4500           0           1
889    0  26.0  30.0000           0           0
890    0  32.0   7.7500           1           0

[891 rows x 5 columns]

In [23]:
df=df.dropna(subset=['age'])

In [24]:
import pandas as pd
df['sex'] = df['sex'].map({'male':0, 'female':1})
df=pd.get_dummies(df, columns=['embarked'], drop_first=True)

/var/folders/sz/167qwb595mqgwry5mm8685n00000gn/T/ipykernel_58701/2997485109.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sex'] = df['sex'].map({'male':0, 'female':1})

In [25]:
X = df[['sex','age','fare','embarked_Q','embarked_S']]
y = df['survived']

In [36]:
## 패키지를 불러오자!
from sklearn.model_selection import cross_val_score
#cross_val_score(model, X,y, cv=교차검증, scoring='평가지표')

#모델도 불러오기
from sklearn.linear_model import LogisticRegression

#로지스틱 베이스 모델 불러오기
model= LogisticRegression(max_iter=200)

#Kfold 교차검증
kf_scores =cross_val_score(model, X, y ,cv=kf, scoring='accuracy')

#Skflold 교차검증
skf_scores =cross_val_score(model, X, y ,cv=skf, scoring='accuracy')

In [34]:
kf_scores

array([0.79020979, 0.7972028 , 0.74825175, 0.73426573, 0.8028169 ])

In [37]:
skf_scores

array([0.72727273, 0.81818182, 0.75524476, 0.73426573, 0.8028169 ])

In [38]:
#교차검증 cv값을 조정할 수 있다.
base_scores =cross_val_score(model, X, y ,cv=5, scoring='accuracy')

In [39]:
base_scores

array([0.72727273, 0.81818182, 0.75524476, 0.73426573, 0.8028169 ])

### 교차검증을 모두 다 정리해서 확인해 보자!

In [40]:
##평가지표 불러오기
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

In [41]:
# 타이타닉 데이터셋 로드
df = sns.load_dataset('titanic')

df=df.dropna(subset=['age'])

df['sex'] = df['sex'].map({'male':0, 'female':1})
df=pd.get_dummies(df, columns=['embarked'], drop_first=True)

# 학습데이터셋 정리

X = df[['sex','age','fare','embarked_Q','embarked_S']]
y = df['survived']


# 처음은 train_test_split 평가

X_train, X_test, y_train, y_test=train_test_split(
    X,y,
    test_size= 0.2,
    random_state=111)


#스케일링 진행
scaler=StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


#로지스틱 베이스 모델 불러오기
model= LogisticRegression(max_iter=200)

#Train, test 결과
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

#train,test 성능평가
accuracy_train_test = accuracy_score(y_test, y_pred)
precision_train_test = precision_score(y_test, y_pred)
recall_train_test = recall_score(y_test, y_pred)
f1_train_test = f1_score(y_test, y_pred)

# 전체 타겟 데이터 분포
overall_target_dist = Counter(y)

# train/test로 분할 했을 때 타겟 분포
train_target_dist = Counter(y_train)
test_target_dist = Counter(y_test)

# Kfold 교차 검증
kf = KFold(n_splits = 5, shuffle=True, random_state=111)
kf_accuracy_scores = cross_val_score(model, X, y ,cv=kf, scoring='accuracy')
kf_precision_scores = cross_val_score(model, X, y ,cv=kf, scoring='precision')
kf_recall_scores = cross_val_score(model, X, y ,cv=kf, scoring='recall')
kf_f1_scores = cross_val_score(model, X, y ,cv=kf, scoring='f1')
#kf 타겟 분포
kf_target_dist = [Counter(y.iloc[test_idx]) for _, test_idx in kf.split(X)]


#skf 교차검증
skf = StratifiedKFold(n_splits = 5, shuffle=True, random_state=111)
skf_accuracy_scores = cross_val_score(model, X, y ,cv=skf, scoring='accuracy')
skf_precision_scores = cross_val_score(model, X, y ,cv=skf, scoring='precision')
skf_recall_scores = cross_val_score(model, X, y ,cv=skf, scoring='recall')
skf_f1_scores = cross_val_score(model, X, y ,cv=skf, scoring='f1')
#Skf 타겟 분포
skf_target_dist = [Counter(y.iloc[test_idx]) for _, test_idx in skf.split(X,y)]

In [42]:
##결과 최종 정리

res = {
    '전체 타겟 분포':overall_target_dist,
    'train/test':{
        'acc':accuracy_train_test,
        'precision':precision_train_test,
        'recall':recall_train_test,
        'f1':f1_train_test,
        'train 타겟 분포':train_target_dist,
        'test 타겟 분포':test_target_dist        
    },
    
        'KFold':{
        'acc':kf_accuracy_scores,
        'precision':kf_precision_scores,
        'recall':kf_recall_scores,
        'f1':kf_f1_scores,
        'KF 타겟 분포':kf_target_dist,
    },
        'SKFold':{
        'acc':skf_accuracy_scores,
        'precision':skf_precision_scores,
        'recall':skf_recall_scores,
        'f1':skf_f1_scores,
        'SKF 타겟 분포':skf_target_dist,
        }
    }

In [43]:
res

{'전체 타겟 분포': Counter({0: 424, 1: 290}),
 'train/test': {'acc': 0.7482517482517482,
  'precision': 0.6610169491525424,
  'recall': 0.7090909090909091,
  'f1': 0.6842105263157895,
  'train 타겟 분포': Counter({0: 336, 1: 235}),
  'test 타겟 분포': Counter({0: 88, 1: 55})},
 'KFold': {'acc': array([0.74825175, 0.78321678, 0.85314685, 0.74125874, 0.75352113]),
  'precision': array([0.66101695, 0.78571429, 0.88888889, 0.70588235, 0.65384615]),
  'recall': array([0.70909091, 0.6984127 , 0.76190476, 0.62068966, 0.66666667]),
  'f1': array([0.68421053, 0.7394958 , 0.82051282, 0.66055046, 0.66019417]),
  'KF 타겟 분포': [Counter({1: 55, 0: 88}),
   Counter({0: 80, 1: 63}),
   Counter({1: 63, 0: 80}),
   Counter({1: 58, 0: 85}),
   Counter({1: 51, 0: 91})]},
 'SKFold': {'acc': array([0.77622378, 0.79020979, 0.74125874, 0.77622378, 0.78873239]),
  'precision': array([0.75      , 0.73333333, 0.69811321, 0.77083333, 0.74137931]),
  'recall': array([0.67241379, 0.75862069, 0.63793103, 0.63793103, 0.74137931]),
  'f1': array([0.70909091, 0.74576271, 0.66666667, 0.69811321, 0.74137931]),
  'SKF 타겟 분포': [Counter({0: 85, 1: 58}),
   Counter({1: 58, 0: 85}),
   Counter({1: 58, 0: 85}),
   Counter({0: 85, 1: 58}),
   Counter({0: 84, 1: 58})]}}